using System.Collections.Generic;

using IPinfo.Models;

namespace IPinfo.Utilities
{
    /// <summary>
    /// CountryHelper class contains country parsing helper methods.
    /// </summary>
    internal static class CountryHelper
    {
        // Static dictionary for countries
        private static readonly Dictionary<string, string> Countries = new Dictionary<string, string>
        {
            {"BD", "Bangladesh"},
            {"BE", "Belgium"},
            {"BF", "Burkina Faso"},
            {"BG", "Bulgaria"},
            {"BA", "Bosnia and Herzegovina"},
            {"BB", "Barbados"},
            {"WF", "Wallis and Futuna"},
            {"BL", "Saint Barthelemy"},
            {"BM", "Bermuda"},
            {"BN", "Brunei"},
            {"BO", "Bolivia"},
            {"BH", "Bahrain"},
            {"BI", "Burundi"},
            {"BJ", "Benin"},
            {"BT", "Bhutan"},
            {"JM", "Jamaica"},
            {"BV", "Bouvet Island"},
            {"BW", "Botswana"},
            {"WS", "Samoa"},
            {"BQ", "Bonaire, Saint Eustatius and Saba "},
            {"BR", "Brazil"},
            {"BS", "Bahamas"},
            {"JE", "Jersey"},
            {"BY", "Belarus"},
            {"BZ", "Belize"},
            {"RU", "Russia"},
            {"RW", "Rwanda"},
            {"RS", "Serbia"},
            {"TL", "East Timor"},
            {"RE", "Reunion"},
            {"TM", "Turkmenistan"},
            {"TJ", "Tajikistan"},
            {"RO", "Romania"},
            {"TK", "Tokelau"},
            {"GW", "Guinea-Bissau"},
            {"GU", "Guam"},
            {"GT", "Guatemala"},
            {"GS", "South Georgia and the South Sandwich Islands"},
            {"GR", "Greece"},
            {"GQ", "Equatorial Guinea"},
            {"GP", "Guadeloupe"},
            {"JP", "Japan"},
            {"GY", "Guyana"},
            {"GG", "Guernsey"},
            {"GF", "French Guiana"},
            {"GE", "Georgia"},
            {"GD", "Grenada"},
            {"GB", "United Kingdom"},
            {"GA", "Gabon"},
            {"SV", "El Salvador"},
            {"GN", "Guinea"},
            {"GM", "Gambia"},
            {"GL", "Greenland"},
            {"GI", "Gibraltar"},
            {"GH", "Ghana"},
            {"OM", "Oman"},
            {"TN", "Tunisia"},
            {"JO", "Jordan"},
            {"HR", "Croatia"},
            {"HT", "Haiti"},
            {"HU", "Hungary"},
            {"HK", "Hong Kong"},
            {"HN", "Honduras"},
            {"HM", "Heard Island and McDonald Islands"},
            {"VE", "Venezuela"},
            {"PR", "Puerto Rico"},
            {"PS", "Palestinian Territory"},
            {"PW", "Palau"},
            {"PT", "Portugal"},
            {"SJ", "Svalbard and Jan Mayen"},
            {"PY", "Paraguay"},
            {"IQ", "Iraq"},
            {"PA", "Panama"},
            {"PF", "French Polynesia"},
            {"PG", "Papua New Guinea"},
            {"PE", "Peru"},
            {"PK", "Pakistan"},
            {"PH", "Philippines"},
            {"PN", "Pitcairn"},
            {"PL", "Poland"},
            {"PM", "Saint Pierre and Miquelon"},
            {"ZM", "Zambia"},
            {"EH", "Western Sahara"},
            {"EE", "Estonia"},
            {"EG", "Egypt"},
            {"ZA", "South Africa"},
            {"EC", "Ecuador"},
            {"IT", "Italy"},
            {"VN", "Vietnam"},
            {"SB", "Solomon Islands"},
            {"ET", "Ethiopia"},
            {"SO", "Somalia"},
            {"ZW", "Zimbabwe"},
            {"SA", "Saudi Arabia"},
            {"ES", "Spain"},
            {"ER", "Eritrea"},
            {"ME", "Montenegro"},
            {"MD", "Moldova"},
            {"MG", "Madagascar"},
            {"MF", "Saint Martin"},
            {"MA", "Morocco"},
            {"MC", "Monaco"},
            {"UZ", "Uzbekistan"},
            {"MM", "Myanmar"},
            {"ML", "Mali"},
            {"MO", "Macao"},
            {"MN", "Mongolia"},
            {"MH", "Marshall Islands"},
            {"MK", "Macedonia"},
            {"MU", "Mauritius"},
            {"MT", "Malta"},
            {"MW", "Malawi"},
            {"MV", "Maldives"},
            {"MQ", "Martinique"},
            {"MP", "Northern Mariana Islands"},
            {"MS", "Montserrat"},
            {"MR", "Mauritania"},
            {"IM", "Isle of Man"},
            {"UG", "Uganda"},
            {"TZ", "Tanzania"},
            {"MY", "Malaysia"},
            {"MX", "Mexico"},
            {"IL", "Israel"},
            {"FR", "France"},
            {"IO", "British Indian Ocean Territory"},
            {"SH", "Saint Helena"},
            {"FI", "Finland"},
            {"FJ", "Fiji"},
            {"FK", "Falkland Islands"},
            {"FM", "Micronesia"},
            {"FO", "Faroe Islands"},
            {"NI", "Nicaragua"},
            {"NL", "Netherlands"},
            {"NO", "Norway"},
            {"NA", "Namibia"},
            {"VU", "Vanuatu"},
            {"NC", "New Caledonia"},
            {"NE", "Niger"},
            {"NF", "Norfolk Island"},
            {"NG", "Nigeria"},
            {"NZ", "New Zealand"},
            {"NP", "Nepal"},
            {"NR", "Nauru"},
            {"NU", "Niue"},
            {"CK", "Cook Islands"},
            {"XK", "Kosovo"},
            {"CI", "Ivory Coast"},
            {"CH", "Switzerland"},
            {"CO", "Colombia"},
            {"CN", "China"},
            {"CM", "Cameroon"},
            {"CL", "Chile"},
            {"CC", "Cocos Islands"},
            {"CA", "Canada"},
            {"CG", "Republic of the Congo"},
            {"CF", "Central African Republic"},
            {"CD", "Democratic Republic of the Congo"},
            {"CZ", "Czech Republic"},
            {"CY", "Cyprus"},
            {"CX", "Christmas Island"},
            {"CR", "Costa Rica"},
            {"CW", "Curacao"},
            {"CV", "Cape Verde"},
            {"CU", "Cuba"},
            {"SZ", "Swaziland"},
            {"SY", "Syria"},
            {"SX", "Sint Maarten"},
            {"KG", "Kyrgyzstan"},
            {"KE", "Kenya"},
            {"SS", "South Sudan"},
            {"SR", "Suriname"},
            {"KI", "Kiribati"},
            {"KH", "Cambodia"},
            {"KN", "Saint Kitts and Nevis"},
            {"KM", "Comoros"},
            {"ST", "Sao Tome and Principe"},
            {"SK", "Slovakia"},
            {"KR", "South Korea"},
            {"SI", "Slovenia"},
            {"KP", "North Korea"},
            {"KW", "Kuwait"},
            {"SN", "Senegal"},
            {"SM", "San Marino"},
            {"SL", "Sierra Leone"},
            {"SC", "Seychelles"},
            {"KZ", "Kazakhstan"},
            {"KY", "Cayman Islands"},
            {"SG", "Singapore"},
            {"SE", "Sweden"},
            {"SD", "Sudan"},
            {"DO", "Dominican Republic"},
            {"DM", "Dominica"},
            {"DJ", "Djibouti"},
            {"DK", "Denmark"},
            {"VG", "British Virgin Islands"},
            {"DE", "Germany"},
            {"YE", "Yemen"},
            {"DZ", "Algeria"},
            {"US", "United States"},
            {"UY", "Uruguay"},
            {"YT", "Mayotte"},
            {"UM", "United States Minor Outlying Islands"},
            {"LB", "Lebanon"},
            {"LC", "Saint Lucia"},
            {"LA", "Laos"},
            {"TV", "Tuvalu"},
            {"TW", "Taiwan"},
            {"TT", "Trinidad and Tobago"},
            {"TR", "Turkey"},
            {"LK", "Sri Lanka"},
            {"LI", "Liechtenstein"},
            {"LV", "Latvia"},
            {"TO", "Tonga"},
            {"LT", "Lithuania"},
            {"LU", "Luxembourg"},
            {"LR", "Liberia"},
            {"LS", "Lesotho"},
            {"TH", "Thailand"},
            {"TF", "French Southern Territories"},
            {"TG", "Togo"},
            {"TD", "Chad"},
            {"TC", "Turks and Caicos Islands"},
            {"LY", "Libya"},
            {"VA", "Vatican"},
            {"VC", "Saint Vincent and the Grenadines"},
            {"AE", "United Arab Emirates"},
            {"AD", "Andorra"},
            {"AG", "Antigua and Barbuda"},
            {"AF", "Afghanistan"},
            {"AI", "Anguilla"},
            {"VI", "U.S. Virgin Islands"},
            {"IS", "Iceland"},
            {"IR", "Iran"},
            {"AM", "Armenia"},
            {"AL", "Albania"},
            {"AO", "Angola"},
            {"AQ", "Antarctica"},
            {"AS", "American Samoa"},
            {"AR", "Argentina"},
            {"AU", "Australia"},
            {"AT", "Austria"},
            {"AW", "Aruba"},
            {"IN", "India"},
            {"AX", "Aland Islands"},
            {"AZ", "Azerbaijan"},
            {"IE", "Ireland"},
            {"ID", "Indonesia"},
            {"UA", "Ukraine"},
            {"QA", "Qatar"},
            {"MZ", "Mozambique"}
        };

        // Static dictionary for country flags
        private static readonly Dictionary<string, CountryFlag> CountriesFlags = new Dictionary<string, CountryFlag>
        {
            {"AD", new CountryFlag { Emoji = "🇦🇩", Unicode = "U+1F1E6 U+1F1E9" }},
            {"AE", new CountryFlag { Emoji = "🇦🇪", Unicode = "U+1F1E6 U+1F1EA" }},
            {"AF", new CountryFlag { Emoji = "🇦🇫", Unicode = "U+1F1E6 U+1F1EB" }},
            {"AG", new CountryFlag { Emoji = "🇦🇬", Unicode = "U+1F1E6 U+1F1EC" }},
            {"AI", new CountryFlag { Emoji = "🇦🇮", Unicode = "U+1F1E6 U+1F1EE" }},
            {"AL", new CountryFlag { Emoji = "🇦🇱", Unicode = "U+1F1E6 U+1F1F1" }},
            {"AM", new CountryFlag { Emoji = "🇦🇲", Unicode = "U+1F1E6 U+1F1F2" }},
            {"AO", new CountryFlag { Emoji = "🇦🇴", Unicode = "U+1F1E6 U+1F1F4" }},
            {"AQ", new CountryFlag { Emoji = "🇦🇶", Unicode = "U+1F1E6 U+1F1F6" }},
            {"AR", new CountryFlag { Emoji = "🇦🇷", Unicode = "U+1F1E6 U+1F1F7" }},
            {"AS", new CountryFlag { Emoji = "🇦🇸", Unicode = "U+1F1E6 U+1F1F8" }},
            {"AT", new CountryFlag { Emoji = "🇦🇹", Unicode = "U+1F1E6 U+1F1F9" }},
            {"AU", new CountryFlag { Emoji = "🇦🇺", Unicode = "U+1F1E6 U+1F1FA" }},
            {"AW", new CountryFlag { Emoji = "🇦🇼", Unicode = "U+1F1E6 U+1F1FC" }},
            {"AX", new CountryFlag { Emoji = "🇦🇽", Unicode = "U+1F1E6 U+1F1FD" }},
            {"AZ", new CountryFlag { Emoji = "🇦🇿", Unicode = "U+1F1E6 U+1F1FF" }},
            {"BA", new CountryFlag { Emoji = "🇧🇦", Unicode = "U+1F1E7 U+1F1E6" }},
            {"BB", new CountryFlag { Emoji = "🇧🇧", Unicode = "U+1F1E7 U+1F1E7" }},
            {"BD", new CountryFlag { Emoji = "🇧🇩", Unicode = "U+1F1E7 U+1F1E9" }},
            {"BE", new CountryFlag { Emoji = "🇧🇪", Unicode = "U+1F1E7 U+1F1EA" }},
            {"BF", new CountryFlag { Emoji = "🇧🇫", Unicode = "U+1F1E7 U+1F1EB" }},
            {"BG", new CountryFlag { Emoji = "🇧🇬", Unicode = "U+1F1E7 U+1F1EC" }},
            {"BH", new CountryFlag { Emoji = "🇧🇭", Unicode = "U+1F1E7 U+1F1ED" }},
            {"BI", new CountryFlag { Emoji = "🇧🇮", Unicode = "U+1F1E7 U+1F1EE" }},
            {"BJ", new CountryFlag { Emoji = "🇧🇯", Unicode = "U+1F1E7 U+1F1EF" }},
            {"BL", new CountryFlag { Emoji = "🇧🇱", Unicode = "U+1F1E7 U+1F1F1" }},
            {"BM", new CountryFlag { Emoji = "🇧🇲", Unicode = "U+1F1E7 U+1F1F2" }},
            {"BN", new CountryFlag { Emoji = "🇧🇳", Unicode = "U+1F1E7 U+1F1F3" }},
            {"BO", new CountryFlag { Emoji = "🇧🇴", Unicode = "U+1F1E7 U+1F1F4" }},
            {"BQ", new CountryFlag { Emoji = "🇧🇶", Unicode = "U+1F1E7 U+1F1F6" }},
            {"BR", new CountryFlag { Emoji = "🇧🇷", Unicode = "U+1F1E7 U+1F1F7" }},
            {"BS", new CountryFlag { Emoji = "🇧🇸", Unicode = "U+1F1E7 U+1F1F8" }},
            {"BT", new CountryFlag { Emoji = "🇧🇹", Unicode = "U+1F1E7 U+1F1F9" }},
            {"BV", new CountryFlag { Emoji = "🇧🇻", Unicode = "U+1F1E7 U+1F1FB" }},
            {"BW", new CountryFlag { Emoji = "🇧🇼", Unicode = "U+1F1E7 U+1F1FC" }},
            {"BY", new CountryFlag { Emoji = "🇧🇾", Unicode = "U+1F1E7 U+1F1FE" }},
            {"BZ", new CountryFlag { Emoji = "🇧🇿", Unicode = "U+1F1E7 U+1F1FF" }},
            {"CA", new CountryFlag { Emoji = "🇨🇦", Unicode = "U+1F1E8 U+1F1E6" }},
            {"CC", new CountryFlag { Emoji = "🇨🇨", Unicode = "U+1F1E8 U+1F1E8" }},
            {"CD", new CountryFlag { Emoji = "🇨🇩", Unicode = "U+1F1E8 U+1F1E9" }},
            {"CF", new CountryFlag { Emoji = "🇨🇫", Unicode = "U+1F1E8 U+1F1EB" }},
            {"CG", new CountryFlag { Emoji = "🇨🇬", Unicode = "U+1F1E8 U+1F1EC" }},
            {"CH", new CountryFlag { Emoji = "🇨🇭", Unicode = "U+1F1E8 U+1F1ED" }},
            {"CI", new CountryFlag { Emoji = "🇨🇮", Unicode = "U+1F1E8 U+1F1EE" }},
            {"CK", new CountryFlag { Emoji = "🇨🇰", Unicode = "U+1F1E8 U+1F1F0" }},
            {"CL", new CountryFlag { Emoji = "🇨🇱", Unicode = "U+1F1E8 U+1F1F1" }},
            {"CM", new CountryFlag { Emoji = "🇨🇲", Unicode = "U+1F1E8 U+1F1F2" }},
            {"CN", new CountryFlag { Emoji = "🇨🇳", Unicode = "U+1F1E8 U+1F1F3" }},
            {"CO", new CountryFlag { Emoji = "🇨🇴", Unicode = "U+1F1E8 U+1F1F4" }},
            {"CR", new CountryFlag { Emoji = "🇨🇷", Unicode = "U+1F1E8 U+1F1F7" }},
            {"CU", new CountryFlag { Emoji = "🇨🇺", Unicode = "U+1F1E8 U+1F1FA" }},
            {"CV", new CountryFlag { Emoji = "🇨🇻", Unicode = "U+1F1E8 U+1F1FB" }},
            {"CW", new CountryFlag { Emoji = "🇨🇼", Unicode = "U+1F1E8 U+1F1FC" }},
            {"CX", new CountryFlag { Emoji = "🇨🇽", Unicode = "U+1F1E8 U+1F1FD" }},
            {"CY", new CountryFlag { Emoji = "🇨🇾", Unicode = "U+1F1E8 U+1F1FE" }},
            {"CZ", new CountryFlag { Emoji = "🇨🇿", Unicode = "U+1F1E8 U+1F1FF" }},
            {"DE", new CountryFlag { Emoji = "🇩🇪", Unicode = "U+1F1E9 U+1F1EA" }},
            {"DJ", new CountryFlag { Emoji = "🇩🇯", Unicode = "U+1F1E9 U+1F1EF" }},
            {"DK", new CountryFlag { Emoji = "🇩🇰", Unicode = "U+1F1E9 U+1F1F0" }},
            {"DM", new CountryFlag { Emoji = "🇩🇲", Unicode = "U+1F1E9 U+1F1F2" }},
            {"DO", new CountryFlag { Emoji = "🇩🇴", Unicode = "U+1F1E9 U+1F1F4" }},
            {"DZ", new CountryFlag { Emoji = "🇩🇿", Unicode = "U+1F1E9 U+1F1FF" }},
            {"EC", new CountryFlag { Emoji = "🇪🇨", Unicode = "U+1F1EA U+1F1E8" }},
            {"EE", new CountryFlag { Emoji = "🇪🇪", Unicode = "U+1F1EA U+1F1EA" }},
            {"EG", new CountryFlag { Emoji = "🇪🇬", Unicode = "U+1F1EA U+1F1EC" }},
            {"EH", new CountryFlag { Emoji = "🇪🇭", Unicode = "U+1F1EA U+1F1ED" }},
            {"ER", new CountryFlag { Emoji = "🇪🇷", Unicode = "U+1F1EA U+1F1F7" }},
            {"ES", new CountryFlag { Emoji = "🇪🇸", Unicode = "U+1F1EA U+1F1F8" }},
            {"ET", new CountryFlag { Emoji = "🇪🇹", Unicode = "U+1F1EA U+1F1F9" }},
            {"FI", new CountryFlag { Emoji = "🇫🇮", Unicode = "U+1F1EB U+1F1EE" }},
            {"FJ", new CountryFlag { Emoji = "🇫🇯", Unicode = "U+1F1EB U+1F1EF" }},
            {"FK", new CountryFlag { Emoji = "🇫🇰", Unicode = "U+1F1EB U+1F1F0" }},
            {"FM", new CountryFlag { Emoji = "🇫🇲", Unicode = "U+1F1EB U+1F1F2" }},
            {"FO", new CountryFlag { Emoji = "🇫🇴", Unicode = "U+1F1EB U+1F1F4" }},
            {"FR", new CountryFlag { Emoji = "🇫🇷", Unicode = "U+1F1EB U+1F1F7" }},
            {"GA", new CountryFlag { Emoji = "🇬🇦", Unicode = "U+1F1EC U+1F1E6" }},
            {"GB", new CountryFlag { Emoji = "🇬🇧", Unicode = "U+1F1EC U+1F1E7" }},
            {"GD", new CountryFlag { Emoji = "🇬🇩", Unicode = "U+1F1EC U+1F1E9" }},
            {"GE", new CountryFlag { Emoji = "🇬🇪", Unicode = "U+1F1EC U+1F1EA" }},
            {"GF", new CountryFlag { Emoji = "🇬🇫", Unicode = "U+1F1EC U+1F1EB" }},
            {"GG", new CountryFlag { Emoji = "🇬🇬", Unicode = "U+1F1EC U+1F1EC" }},
            {"GH", new CountryFlag { Emoji = "🇬🇭", Unicode = "U+1F1EC U+1F1ED" }},
            {"GI", new CountryFlag { Emoji = "🇬🇮", Unicode = "U+1F1EC U+1F1EE" }},
            {"GL", new CountryFlag { Emoji = "🇬🇱", Unicode = "U+1F1EC U+1F1F1" }},
            {"GM", new CountryFlag { Emoji = "🇬🇲", Unicode = "U+1F1EC U+1F1F2" }},
            {"GN", new CountryFlag { Emoji = "🇬🇳", Unicode = "U+1F1EC U+1F1F3" }},
            {"GP", new CountryFlag { Emoji = "🇬🇵", Unicode = "U+1F1EC U+1F1F5" }},
            {"GQ", new CountryFlag { Emoji = "🇬🇶", Unicode = "U+1F1EC U+1F1F6" }},
            {"GR", new CountryFlag { Emoji = "🇬🇷", Unicode = "U+1F1EC U+1F1F7" }},
            {"GS", new CountryFlag { Emoji = "🇬🇸", Unicode = "U+1F1EC U+1F1F8" }},
            {"GT", new CountryFlag { Emoji = "🇬🇹", Unicode = "U+1F1EC U+1F1F9" }},
            {"GU", new CountryFlag { Emoji = "🇬🇺", Unicode = "U+1F1EC U+1F1FA" }},
            {"GW", new CountryFlag { Emoji = "🇬🇼", Unicode = "U+1F1EC U+1F1FC" }},
            {"GY", new CountryFlag { Emoji = "🇬🇾", Unicode = "U+1F1EC U+1F1FE" }},
            {"HK", new CountryFlag { Emoji = "🇭🇰", Unicode = "U+1F1ED U+1F1F0" }},
            {"HM", new CountryFlag { Emoji = "🇭🇲", Unicode = "U+1F1ED U+1F1F2" }},
            {"HN", new CountryFlag { Emoji = "🇭🇳", Unicode = "U+1F1ED U+1F1F3" }},
            {"HR", new CountryFlag { Emoji = "🇭🇷", Unicode = "U+1F1ED U+1F1F7" }},
            {"HT", new CountryFlag { Emoji = "🇭🇹", Unicode = "U+1F1ED U+1F1F9" }},
            {"HU", new CountryFlag { Emoji = "🇭🇺", Unicode = "U+1F1ED U+1F1FA" }},
            {"ID", new CountryFlag { Emoji = "🇮🇩", Unicode = "U+1F1EE U+1F1E9" }},
            {"IE", new CountryFlag { Emoji = "🇮🇪", Unicode = "U+1F1EE U+1F1EA" }},
            {"IL", new CountryFlag { Emoji = "🇮🇱", Unicode = "U+1F1EE U+1F1F1" }},
            {"IM", new CountryFlag { Emoji = "🇮🇲", Unicode = "U+1F1EE U+1F1F2" }},
            {"IN", new CountryFlag { Emoji = "🇮🇳", Unicode = "U+1F1EE U+1F1F3" }},
            {"IO", new CountryFlag { Emoji = "🇮🇴", Unicode = "U+1F1EE U+1F1F4" }},
            {"IQ", new CountryFlag { Emoji = "🇮🇶", Unicode = "U+1F1EE U+1F1F6" }},
            {"IR", new CountryFlag { Emoji = "🇮🇷", Unicode = "U+1F1EE U+1F1F7" }},
            {"IS", new CountryFlag { Emoji = "🇮🇸", Unicode = "U+1F1EE U+1F1F8" }},
            {"IT", new CountryFlag { Emoji = "🇮🇹", Unicode = "U+1F1EE U+1F1F9" }},
            {"JE", new CountryFlag { Emoji = "🇯🇪", Unicode = "U+1F1EF U+1F1EA" }},
            {"JM", new CountryFlag { Emoji = "🇯🇲", Unicode = "U+1F1EF U+1F1F2" }},
            {"JO", new CountryFlag { Emoji = "🇯🇴", Unicode = "U+1F1EF U+1F1F4" }},
            {"JP", new CountryFlag { Emoji = "🇯🇵", Unicode = "U+1F1EF U+1F1F5" }},
            {"KE", new CountryFlag { Emoji = "🇰🇪", Unicode = "U+1F1F0 U+1F1EA" }},
            {"KG", new CountryFlag { Emoji = "🇰🇬", Unicode = "U+1F1F0 U+1F1EC" }},
            {"KH", new CountryFlag { Emoji = "🇰🇭", Unicode = "U+1F1F0 U+1F1ED" }},
            {"KI", new CountryFlag { Emoji = "🇰🇮", Unicode = "U+1F1F0 U+1F1EE" }},
            {"KM", new CountryFlag { Emoji = "🇰🇲", Unicode = "U+1F1F0 U+1F1F2" }},
            {"KN", new CountryFlag { Emoji = "🇰🇳", Unicode = "U+1F1F0 U+1F1F3" }},
            {"KP", new CountryFlag { Emoji = "🇰🇵", Unicode = "U+1F1F0 U+1F1F5" }},
            {"KR", new CountryFlag { Emoji = "🇰🇷", Unicode = "U+1F1F0 U+1F1F7" }},
            {"KW", new CountryFlag { Emoji = "🇰🇼", Unicode = "U+1F1F0 U+1F1FC" }},
            {"KY", new CountryFlag { Emoji = "🇰🇾", Unicode = "U+1F1F0 U+1F1FE" }},
            {"KZ", new CountryFlag { Emoji = "🇰🇿", Unicode = "U+1F1F0 U+1F1FF" }},
            {"LA", new CountryFlag { Emoji = "🇱🇦", Unicode = "U+1F1F1 U+1F1E6" }},
            {"LB", new CountryFlag { Emoji = "🇱🇧", Unicode = "U+1F1F1 U+1F1E7" }},
            {"LC", new CountryFlag { Emoji = "🇱🇨", Unicode = "U+1F1F1 U+1F1E8" }},
            {"LI", new CountryFlag { Emoji = "🇱🇮", Unicode = "U+1F1F1 U+1F1EE" }},
            {"LK", new CountryFlag { Emoji = "🇱🇰", Unicode = "U+1F1F1 U+1F1F0" }},
            {"LR", new CountryFlag { Emoji = "🇱🇷", Unicode = "U+1F1F1 U+1F1F7" }},
            {"LS", new CountryFlag { Emoji = "🇱🇸", Unicode = "U+1F1F1 U+1F1F8" }},
            {"LT", new CountryFlag { Emoji = "🇱🇹", Unicode = "U+1F1F1 U+1F1F9" }},
            {"LU", new CountryFlag { Emoji = "🇱🇺", Unicode = "U+1F1F1 U+1F1FA" }},
            {"LV", new CountryFlag { Emoji = "🇱🇻", Unicode = "U+1F1F1 U+1F1FB" }},
            {"LY", new CountryFlag { Emoji = "🇱🇾", Unicode = "U+1F1F1 U+1F1FE" }},
            {"MA", new CountryFlag { Emoji = "🇲🇦", Unicode = "U+1F1F2 U+1F1E6" }},
            {"MC", new CountryFlag { Emoji = "🇲🇨", Unicode = "U+1F1F2 U+1F1E8" }},
            {"MD", new CountryFlag { Emoji = "🇲🇩", Unicode = "U+1F1F2 U+1F1E9" }},
            {"ME", new CountryFlag { Emoji = "🇲🇪", Unicode = "U+1F1F2 U+1F1EA" }},
            {"MF", new CountryFlag { Emoji = "🇲🇫", Unicode = "U+1F1F2 U+1F1EB" }},
            {"MG", new CountryFlag { Emoji = "🇲🇬", Unicode = "U+1F1F2 U+1F1EC" }},
            {"MH", new CountryFlag { Emoji = "🇲🇭", Unicode = "U+1F1F2 U+1F1ED" }},
            {"MK", new CountryFlag { Emoji = "🇲🇰", Unicode = "U+1F1F2 U+1F1F0" }},
            {"ML", new CountryFlag { Emoji = "🇲🇱", Unicode = "U+1F1F2 U+1F1F1" }},
            {"MM", new CountryFlag { Emoji = "🇲🇲", Unicode = "U+1F1F2 U+1F1F2" }},
            {"MN", new CountryFlag { Emoji = "🇲🇳", Unicode = "U+1F1F2 U+1F1F3" }},
            {"MO", new CountryFlag { Emoji = "🇲🇴", Unicode = "U+1F1F2 U+1F1F4" }},
            {"MP", new CountryFlag { Emoji = "🇲🇵", Unicode = "U+1F1F2 U+1F1F5" }},
            {"MQ", new CountryFlag { Emoji = "🇲🇶", Unicode = "U+1F1F2 U+1F1F6" }},
            {"MR", new CountryFlag { Emoji = "🇲🇷", Unicode = "U+1F1F2 U+1F1F7" }},
            {"MS", new CountryFlag { Emoji = "🇲🇸", Unicode = "U+1F1F2 U+1F1F8" }},
            {"MT", new CountryFlag { Emoji = "🇲🇹", Unicode = "U+1F1F2 U+1F1F9" }},
            {"MU", new CountryFlag { Emoji = "🇲🇺", Unicode = "U+1F1F2 U+1F1FA" }},
            {"MV", new CountryFlag { Emoji = "🇲🇻", Unicode = "U+1F1F2 U+1F1FB" }},
            {"MW", new CountryFlag { Emoji = "🇲🇼", Unicode = "U+1F1F2 U+1F1FC" }},
            {"MX", new CountryFlag { Emoji = "🇲🇽", Unicode = "U+1F1F2 U+1F1FD" }},
            {"MY", new CountryFlag { Emoji = "🇲🇾", Unicode = "U+1F1F2 U+1F1FE" }},
            {"MZ", new CountryFlag { Emoji = "🇲🇿", Unicode = "U+1F1F2 U+1F1FF" }},
            {"NA", new CountryFlag { Emoji = "🇳🇦", Unicode = "U+1F1F3 U+1F1E6" }},
            {"NC", new CountryFlag { Emoji = "🇳🇨", Unicode = "U+1F1F3 U+1F1E8" }},
            {"NE", new CountryFlag { Emoji = "🇳🇪", Unicode = "U+1F1F3 U+1F1EA" }},
            {"NF", new CountryFlag { Emoji = "🇳🇫", Unicode = "U+1F1F3 U+1F1EB" }},
            {"NG", new CountryFlag { Emoji = "🇳🇬", Unicode = "U+1F1F3 U+1F1EC" }},
            {"NI", new CountryFlag { Emoji = "🇳🇮", Unicode = "U+1F1F3 U+1F1EE" }},
            {"NL", new CountryFlag { Emoji = "🇳🇱", Unicode = "U+1F1F3 U+1F1F1" }},
            {"NO", new CountryFlag { Emoji = "🇳🇴", Unicode = "U+1F1F3 U+1F1F4" }},
            {"NP", new CountryFlag { Emoji = "🇳🇵", Unicode = "U+1F1F3 U+1F1F5" }},
            {"NR", new CountryFlag { Emoji = "🇳🇷", Unicode = "U+1F1F3 U+1F1F7" }},
            {"NU", new CountryFlag { Emoji = "🇳🇺", Unicode = "U+1F1F3 U+1F1FA" }},
            {"NZ", new CountryFlag { Emoji = "🇳🇿", Unicode = "U+1F1F3 U+1F1FF" }},
            {"OM", new CountryFlag { Emoji = "🇴🇲", Unicode = "U+1F1F4 U+1F1F2" }},
            {"PA", new CountryFlag { Emoji = "🇵🇦", Unicode = "U+1F1F5 U+1F1E6" }},
            {"PE", new CountryFlag { Emoji = "🇵🇪", Unicode = "U+1F1F5 U+1F1EA" }},
            {"PF", new CountryFlag { Emoji = "🇵🇫", Unicode = "U+1F1F5 U+1F1EB" }},
            {"PG", new CountryFlag { Emoji = "🇵🇬", Unicode = "U+1F1F5 U+1F1EC" }},
            {"PH", new CountryFlag { Emoji = "🇵🇭", Unicode = "U+1F1F5 U+1F1ED" }},
            {"PK", new CountryFlag { Emoji = "🇵🇰", Unicode = "U+1F1F5 U+1F1F0" }},
            {"PL", new CountryFlag { Emoji = "🇵🇱", Unicode = "U+1F1F5 U+1F1F1" }},
            {"PM", new CountryFlag { Emoji = "🇵🇲", Unicode = "U+1F1F5 U+1F1F2" }},
            {"PN", new CountryFlag { Emoji = "🇵🇳", Unicode = "U+1F1F5 U+1F1F3" }},
            {"PR", new CountryFlag { Emoji = "🇵🇷", Unicode = "U+1F1F5 U+1F1F7" }},
            {"PS", new CountryFlag { Emoji = "🇵🇸", Unicode = "U+1F1F5 U+1F1F8" }},
            {"PT", new CountryFlag { Emoji = "🇵🇹", Unicode = "U+1F1F5 U+1F1F9" }},
            {"PW", new CountryFlag { Emoji = "🇵🇼", Unicode = "U+1F1F5 U+1F1FC" }},
            {"PY", new CountryFlag { Emoji = "🇵🇾", Unicode = "U+1F1F5 U+1F1FE" }},
            {"QA", new CountryFlag { Emoji = "🇶🇦", Unicode = "U+1F1F6 U+1F1E6" }},
            {"RE", new CountryFlag { Emoji = "🇷🇪", Unicode = "U+1F1F7 U+1F1EA" }},
            {"RO", new CountryFlag { Emoji = "🇷🇴", Unicode = "U+1F1F7 U+1F1F4" }},
            {"RS", new CountryFlag { Emoji = "🇷🇸", Unicode = "U+1F1F7 U+1F1F8" }},
            {"RU", new CountryFlag { Emoji = "🇷🇺", Unicode = "U+1F1F7 U+1F1FA" }},
            {"RW", new CountryFlag { Emoji = "🇷🇼", Unicode = "U+1F1F7 U+1F1FC" }},
            {"SA", new CountryFlag { Emoji = "🇸🇦", Unicode = "U+1F1F8 U+1F1E6" }},
            {"SB", new CountryFlag { Emoji = "🇸🇧", Unicode = "U+1F1F8 U+1F1E7" }},
            {"SC", new CountryFlag { Emoji = "🇸🇨", Unicode = "U+1F1F8 U+1F1E8" }},
            {"SD", new CountryFlag { Emoji = "🇸🇩", Unicode = "U+1F1F8 U+1F1E9" }},
            {"SE", new CountryFlag { Emoji = "🇸🇪", Unicode = "U+1F1F8 U+1F1EA" }},
            {"SG", new CountryFlag { Emoji = "🇸🇬", Unicode = "U+1F1F8 U+1F1EC" }},
            {"SH", new CountryFlag { Emoji = "🇸🇭", Unicode = "U+1F1F8 U+1F1ED" }},
            {"SI", new CountryFlag { Emoji = "🇸🇮", Unicode = "U+1F1F8 U+1F1EE" }},
            {"SJ", new CountryFlag { Emoji = "🇸🇯", Unicode = "U+1F1F8 U+1F1EF" }},
            {"SK", new CountryFlag { Emoji = "🇸🇰", Unicode = "U+1F1F8 U+1F1F0" }},
            {"SL", new CountryFlag { Emoji = "🇸🇱", Unicode = "U+1F1F8 U+1F1F1" }},
            {"SM", new CountryFlag { Emoji = "🇸🇲", Unicode = "U+1F1F8 U+1F1F2" }},
            {"SN", new CountryFlag { Emoji = "🇸🇳", Unicode = "U+1F1F8 U+1F1F3" }},
            {"SO", new CountryFlag { Emoji = "🇸🇴", Unicode = "U+1F1F8 U+1F1F4" }},
            {"SR", new CountryFlag { Emoji = "🇸🇷", Unicode = "U+1F1F8 U+1F1F7" }},
            {"SS", new CountryFlag { Emoji = "🇸🇸", Unicode = "U+1F1F8 U+1F1F8" }},
            {"ST", new CountryFlag { Emoji = "🇸🇹", Unicode = "U+1F1F8 U+1F1F9" }},
            {"SV", new CountryFlag { Emoji = "🇸🇻", Unicode = "U+1F1F8 U+1F1FB" }},
            {"SX", new CountryFlag { Emoji = "🇸🇽", Unicode = "U+1F1F8 U+1F1FD" }},
            {"SY", new CountryFlag { Emoji = "🇸🇾", Unicode = "U+1F1F8 U+1F1FE" }},
            {"SZ", new CountryFlag { Emoji = "🇸🇿", Unicode = "U+1F1F8 U+1F1FF" }},
            {"TC", new CountryFlag { Emoji = "🇹🇨", Unicode = "U+1F1F9 U+1F1E8" }},
            {"TD", new CountryFlag { Emoji = "🇹🇩", Unicode = "U+1F1F9 U+1F1E9" }},
            {"TF", new CountryFlag { Emoji = "🇹🇫", Unicode = "U+1F1F9 U+1F1EB" }},
            {"TG", new CountryFlag { Emoji = "🇹🇬", Unicode = "U+1F1F9 U+1F1EC" }},
            {"TH", new CountryFlag { Emoji = "🇹🇭", Unicode = "U+1F1F9 U+1F1ED" }},
            {"TJ", new CountryFlag { Emoji = "🇹🇯", Unicode = "U+1F1F9 U+1F1EF" }},
            {"TK", new CountryFlag { Emoji = "🇹🇰", Unicode = "U+1F1F9 U+1F1F0" }},
            {"TL", new CountryFlag { Emoji = "🇹🇱", Unicode = "U+1F1F9 U+1F1F1" }},
            {"TM", new CountryFlag { Emoji = "🇹🇲", Unicode = "U+1F1F9 U+1F1F2" }},
            {"TN", new CountryFlag { Emoji = "🇹🇳", Unicode = "U+1F1F9 U+1F1F3" }},
            {"TO", new CountryFlag { Emoji = "🇹🇴", Unicode = "U+1F1F9 U+1F1F4" }},
            {"TR", new CountryFlag { Emoji = "🇹🇷", Unicode = "U+1F1F9 U+1F1F7" }},
            {"TT", new CountryFlag { Emoji = "🇹🇹", Unicode = "U+1F1F9 U+1F1F9" }},
            {"TV", new CountryFlag { Emoji = "🇹🇻", Unicode = "U+1F1F9 U+1F1FB" }},
            {"TW", new CountryFlag { Emoji = "🇹🇼", Unicode = "U+1F1F9 U+1F1FC" }},
            {"TZ", new CountryFlag { Emoji = "🇹🇿", Unicode = "U+1F1F9 U+1F1FF" }},
            {"UA", new CountryFlag { Emoji = "🇺🇦", Unicode = "U+1F1FA U+1F1E6" }},
            {"UG", new CountryFlag { Emoji = "🇺🇬", Unicode = "U+1F1FA U+1F1EC" }},
            {"UM", new CountryFlag { Emoji = "🇺🇲", Unicode = "U+1F1FA U+1F1F2" }},
            {"US", new CountryFlag { Emoji = "🇺🇸", Unicode = "U+1F1FA U+1F1F8" }},
            {"UY", new CountryFlag { Emoji = "🇺🇾", Unicode = "U+1F1FA U+1F1FE" }},
            {"UZ", new CountryFlag { Emoji = "🇺🇿", Unicode = "U+1F1FA U+1F1FF" }},
            {"VA", new CountryFlag { Emoji = "🇻🇦", Unicode = "U+1F1FB U+1F1E6" }},
            {"VC", new CountryFlag { Emoji = "🇻🇨", Unicode = "U+1F1FB U+1F1E8" }},
            {"VE", new CountryFlag { Emoji = "🇻🇪", Unicode = "U+1F1FB U+1F1EA" }},
            {"VG", new CountryFlag { Emoji = "🇻🇬", Unicode = "U+1F1FB U+1F1EC" }},
            {"VI", new CountryFlag { Emoji = "🇻🇮", Unicode = "U+1F1FB U+1F1EE" }},
            {"VN", new CountryFlag { Emoji = "🇻🇳", Unicode = "U+1F1FB U+1F1F3" }},
            {"VU", new CountryFlag { Emoji = "🇻🇺", Unicode = "U+1F1FB U+1F1FA" }},
            {"WF", new CountryFlag { Emoji = "🇼🇫", Unicode = "U+1F1FC U+1F1EB" }},
            {"WS", new CountryFlag { Emoji = "🇼🇸", Unicode = "U+1F1FC U+1F1F8" }},
            {"XK", new CountryFlag { Emoji = "🇽🇰", Unicode = "U+1F1FD U+1F1F0" }},
            {"YE", new CountryFlag { Emoji = "🇾🇪", Unicode = "U+1F1FE U+1F1EA" }},
            {"YT", new CountryFlag { Emoji = "🇾🇹", Unicode = "U+1F1FE U+1F1F9" }},
            {"ZA", new CountryFlag { Emoji = "🇿🇦", Unicode = "U+1F1FF U+1F1E6" }},
            {"ZM", new CountryFlag { Emoji = "🇿🇲", Unicode = "U+1F1FF U+1F1F2" }},
            {"ZW", new CountryFlag { Emoji = "🇿🇼", Unicode = "U+1F1FF U+1F1FC" }}
        };

        // Static dictionary for country currencies
        private static readonly Dictionary<string, CountryCurrency> CountriesCurrencies = new Dictionary<string, CountryCurrency>
        {
            {"AD", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"AE", new CountryCurrency { Code = "AED", Symbol = "د.إ" }},
            {"AF", new CountryCurrency { Code = "AFN", Symbol = "؋" }},
            {"AG", new CountryCurrency { Code = "XCD", Symbol = "$" }},
            {"AI", new CountryCurrency { Code = "XCD", Symbol = "$" }},
            {"AL", new CountryCurrency { Code = "ALL", Symbol = "L" }},
            {"AM", new CountryCurrency { Code = "AMD", Symbol = "֏" }},
            {"AO", new CountryCurrency { Code = "AOA", Symbol = "Kz" }},
            {"AQ", new CountryCurrency { Code = "", Symbol = "$" }},
            {"AR", new CountryCurrency { Code = "ARS", Symbol = "$" }},
            {"AS", new CountryCurrency { Code = "USD", Symbol = "$" }},
            {"AT", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"AU", new CountryCurrency { Code = "AUD", Symbol = "$" }},
            {"AW", new CountryCurrency { Code = "AWG", Symbol = "ƒ" }},
            {"AX", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"AZ", new CountryCurrency { Code = "AZN", Symbol = "₼" }},
            {"BA", new CountryCurrency { Code = "BAM", Symbol = "KM" }},
            {"BB", new CountryCurrency { Code = "BBD", Symbol = "$" }},
            {"BD", new CountryCurrency { Code = "BDT", Symbol = "৳" }},
            {"BE", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"BF", new CountryCurrency { Code = "XOF", Symbol = "CFA" }},
            {"BG", new CountryCurrency { Code = "BGN", Symbol = "лв" }},
            {"BH", new CountryCurrency { Code = "BHD", Symbol = ".د.ب" }},
            {"BI", new CountryCurrency { Code = "BIF", Symbol = "FBu" }},
            {"BJ", new CountryCurrency { Code = "XOF", Symbol = "CFA" }},
            {"BL", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"BM", new CountryCurrency { Code = "BMD", Symbol = "$" }},
            {"BN", new CountryCurrency { Code = "BND", Symbol = "$" }},
            {"BO", new CountryCurrency { Code = "BOB", Symbol = "$b" }},
            {"BQ", new CountryCurrency { Code = "USD", Symbol = "$" }},
            {"BR", new CountryCurrency { Code = "BRL", Symbol = "R$" }},
            {"BS", new CountryCurrency { Code = "BSD", Symbol = "$" }},
            {"BT", new CountryCurrency { Code = "BTN", Symbol = "Nu." }},
            {"BV", new CountryCurrency { Code = "NOK", Symbol = "kr" }},
            {"BW", new CountryCurrency { Code = "BWP", Symbol = "P" }},
            {"BY", new CountryCurrency { Code = "BYR", Symbol = "Br" }},
            {"BZ", new CountryCurrency { Code = "BZD", Symbol = "BZ$" }},
            {"CA", new CountryCurrency { Code = "CAD", Symbol = "$" }},
            {"CC", new CountryCurrency { Code = "AUD", Symbol = "$" }},
            {"CD", new CountryCurrency { Code = "CDF", Symbol = "FC" }},
            {"CF", new CountryCurrency { Code = "XAF", Symbol = "FCFA" }},
            {"CG", new CountryCurrency { Code = "XAF", Symbol = "FCFA" }},
            {"CH", new CountryCurrency { Code = "CHF", Symbol = "CHF" }},
            {"CI", new CountryCurrency { Code = "XOF", Symbol = "CFA" }},
            {"CK", new CountryCurrency { Code = "NZD", Symbol = "$" }},
            {"CL", new CountryCurrency { Code = "CLP", Symbol = "$" }},
            {"CM", new CountryCurrency { Code = "XAF", Symbol = "FCFA" }},
            {"CN", new CountryCurrency { Code = "CNY", Symbol = "¥" }},
            {"CO", new CountryCurrency { Code = "COP", Symbol = "$" }},
            {"CR", new CountryCurrency { Code = "CRC", Symbol = "₡" }},
            {"CU", new CountryCurrency { Code = "CUP", Symbol = "₱" }},
            {"CV", new CountryCurrency { Code = "CVE", Symbol = "$" }},
            {"CW", new CountryCurrency { Code = "ANG", Symbol = "ƒ" }},
            {"CX", new CountryCurrency { Code = "AUD", Symbol = "$" }},
            {"CY", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"CZ", new CountryCurrency { Code = "CZK", Symbol = "Kč" }},
            {"DE", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"DJ", new CountryCurrency { Code = "DJF", Symbol = "Fdj" }},
            {"DK", new CountryCurrency { Code = "DKK", Symbol = "kr" }},
            {"DM", new CountryCurrency { Code = "XCD", Symbol = "$" }},
            {"DO", new CountryCurrency { Code = "DOP", Symbol = "RD$" }},
            {"DZ", new CountryCurrency { Code = "DZD", Symbol = "دج" }},
            {"EC", new CountryCurrency { Code = "USD", Symbol = "$" }},
            {"EE", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"EG", new CountryCurrency { Code = "EGP", Symbol = "£" }},
            {"EH", new CountryCurrency { Code = "MAD", Symbol = "MAD" }},
            {"ER", new CountryCurrency { Code = "ERN", Symbol = "Nfk" }},
            {"ES", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"ET", new CountryCurrency { Code = "ETB", Symbol = "Br" }},
            {"FI", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"FJ", new CountryCurrency { Code = "FJD", Symbol = "$" }},
            {"FK", new CountryCurrency { Code = "FKP", Symbol = "£" }},
            {"FM", new CountryCurrency { Code = "USD", Symbol = "$" }},
            {"FO", new CountryCurrency { Code = "DKK", Symbol = "kr" }},
            {"FR", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"GA", new CountryCurrency { Code = "XAF", Symbol = "FCFA" }},
            {"GB", new CountryCurrency { Code = "GBP", Symbol = "£" }},
            {"GD", new CountryCurrency { Code = "XCD", Symbol = "$" }},
            {"GE", new CountryCurrency { Code = "GEL", Symbol = "ლ" }},
            {"GF", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"GG", new CountryCurrency { Code = "GBP", Symbol = "£" }},
            {"GH", new CountryCurrency { Code = "GHS", Symbol = "GH₵" }},
            {"GI", new CountryCurrency { Code = "GIP", Symbol = "£" }},
            {"GL", new CountryCurrency { Code = "DKK", Symbol = "kr" }},
            {"GM", new CountryCurrency { Code = "GMD", Symbol = "D" }},
            {"GN", new CountryCurrency { Code = "GNF", Symbol = "FG" }},
            {"GP", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"GQ", new CountryCurrency { Code = "XAF", Symbol = "FCFA" }},
            {"GR", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"GS", new CountryCurrency { Code = "GBP", Symbol = "£" }},
            {"GT", new CountryCurrency { Code = "GTQ", Symbol = "Q" }},
            {"GU", new CountryCurrency { Code = "USD", Symbol = "$" }},
            {"GW", new CountryCurrency { Code = "XOF", Symbol = "CFA" }},
            {"GY", new CountryCurrency { Code = "GYD", Symbol = "$" }},
            {"HK", new CountryCurrency { Code = "HKD", Symbol = "$" }},
            {"HM", new CountryCurrency { Code = "AUD", Symbol = "$" }},
            {"HN", new CountryCurrency { Code = "HNL", Symbol = "L" }},
            {"HR", new CountryCurrency { Code = "HRK", Symbol = "kn" }},
            {"HT", new CountryCurrency { Code = "HTG", Symbol = "G" }},
            {"HU", new CountryCurrency { Code = "HUF", Symbol = "Ft" }},
            {"ID", new CountryCurrency { Code = "IDR", Symbol = "Rp" }},
            {"IE", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"IL", new CountryCurrency { Code = "ILS", Symbol = "₪" }},
            {"IM", new CountryCurrency { Code = "GBP", Symbol = "£" }},
            {"IN", new CountryCurrency { Code = "INR", Symbol = "₹" }},
            {"IO", new CountryCurrency { Code = "USD", Symbol = "$" }},
            {"IQ", new CountryCurrency { Code = "IQD", Symbol = "ع.د" }},
            {"IR", new CountryCurrency { Code = "IRR", Symbol = "﷼" }},
            {"IS", new CountryCurrency { Code = "ISK", Symbol = "kr" }},
            {"IT", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"JE", new CountryCurrency { Code = "GBP", Symbol = "£" }},
            {"JM", new CountryCurrency { Code = "JMD", Symbol = "J$" }},
            {"JO", new CountryCurrency { Code = "JOD", Symbol = "JD" }},
            {"JP", new CountryCurrency { Code = "JPY", Symbol = "¥" }},
            {"KE", new CountryCurrency { Code = "KES", Symbol = "KSh" }},
            {"KG", new CountryCurrency { Code = "KGS", Symbol = "лв" }},
            {"KH", new CountryCurrency { Code = "KHR", Symbol = "៛" }},
            {"KI", new CountryCurrency { Code = "AUD", Symbol = "$" }},
            {"KM", new CountryCurrency { Code = "KMF", Symbol = "CF" }},
            {"KN", new CountryCurrency { Code = "XCD", Symbol = "$" }},
            {"KP", new CountryCurrency { Code = "KPW", Symbol = "₩" }},
            {"KR", new CountryCurrency { Code = "KRW", Symbol = "₩" }},
            {"KW", new CountryCurrency { Code = "KWD", Symbol = "KD" }},
            {"KY", new CountryCurrency { Code = "KYD", Symbol = "$" }},
            {"KZ", new CountryCurrency { Code = "KZT", Symbol = "₸" }},
            {"LA", new CountryCurrency { Code = "LAK", Symbol = "₭" }},
            {"LB", new CountryCurrency { Code = "LBP", Symbol = "£" }},
            {"LC", new CountryCurrency { Code = "XCD", Symbol = "$" }},
            {"LI", new CountryCurrency { Code = "CHF", Symbol = "CHF" }},
            {"LK", new CountryCurrency { Code = "LKR", Symbol = "₨" }},
            {"LR", new CountryCurrency { Code = "LRD", Symbol = "$" }},
            {"LS", new CountryCurrency { Code = "LSL", Symbol = "M" }},
            {"LT", new CountryCurrency { Code = "LTL", Symbol = "Lt" }},
            {"LU", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"LV", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"LY", new CountryCurrency { Code = "LYD", Symbol = "LD" }},
            {"MA", new CountryCurrency { Code = "MAD", Symbol = "MAD" }},
            {"MC", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"MD", new CountryCurrency { Code = "MDL", Symbol = "lei" }},
            {"ME", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"MF", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"MG", new CountryCurrency { Code = "MGA", Symbol = "Ar" }},
            {"MH", new CountryCurrency { Code = "USD", Symbol = "$" }},
            {"MK", new CountryCurrency { Code = "MKD", Symbol = "ден" }},
            {"ML", new CountryCurrency { Code = "XOF", Symbol = "CFA" }},
            {"MM", new CountryCurrency { Code = "MMK", Symbol = "K" }},
            {"MN", new CountryCurrency { Code = "MNT", Symbol = "₮" }},
            {"MO", new CountryCurrency { Code = "MOP", Symbol = "MOP$" }},
            {"MP", new CountryCurrency { Code = "USD", Symbol = "$" }},
            {"MQ", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"MR", new CountryCurrency { Code = "MRO", Symbol = "UM" }},
            {"MS", new CountryCurrency { Code = "XCD", Symbol = "$" }},
            {"MT", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"MU", new CountryCurrency { Code = "MUR", Symbol = "₨" }},
            {"MV", new CountryCurrency { Code = "MVR", Symbol = "Rf" }},
            {"MW", new CountryCurrency { Code = "MWK", Symbol = "MK" }},
            {"MX", new CountryCurrency { Code = "MXN", Symbol = "$" }},
            {"MY", new CountryCurrency { Code = "MYR", Symbol = "RM" }},
            {"MZ", new CountryCurrency { Code = "MZN", Symbol = "MT" }},
            {"NA", new CountryCurrency { Code = "NAD", Symbol = "$" }},
            {"NC", new CountryCurrency { Code = "XPF", Symbol = "₣" }},
            {"NE", new CountryCurrency { Code = "XOF", Symbol = "CFA" }},
            {"NF", new CountryCurrency { Code = "AUD", Symbol = "$" }},
            {"NG", new CountryCurrency { Code = "NGN", Symbol = "₦" }},
            {"NI", new CountryCurrency { Code = "NIO", Symbol = "C$" }},
            {"NL", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"NO", new CountryCurrency { Code = "NOK", Symbol = "kr" }},
            {"NP", new CountryCurrency { Code = "NPR", Symbol = "₨" }},
            {"NR", new CountryCurrency { Code = "AUD", Symbol = "$" }},
            {"NU", new CountryCurrency { Code = "NZD", Symbol = "$" }},
            {"NZ", new CountryCurrency { Code = "NZD", Symbol = "$" }},
            {"OM", new CountryCurrency { Code = "OMR", Symbol = "﷼" }},
            {"PA", new CountryCurrency { Code = "PAB", Symbol = "B/." }},
            {"PE", new CountryCurrency { Code = "PEN", Symbol = "S/." }},
            {"PF", new CountryCurrency { Code = "XPF", Symbol = "₣" }},
            {"PG", new CountryCurrency { Code = "PGK", Symbol = "K" }},
            {"PH", new CountryCurrency { Code = "PHP", Symbol = "₱" }},
            {"PK", new CountryCurrency { Code = "PKR", Symbol = "₨" }},
            {"PL", new CountryCurrency { Code = "PLN", Symbol = "zł" }},
            {"PM", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"PN", new CountryCurrency { Code = "NZD", Symbol = "$" }},
            {"PR", new CountryCurrency { Code = "USD", Symbol = "$" }},
            {"PS", new CountryCurrency { Code = "ILS", Symbol = "₪" }},
            {"PT", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"PW", new CountryCurrency { Code = "USD", Symbol = "$" }},
            {"PY", new CountryCurrency { Code = "PYG", Symbol = "Gs" }},
            {"QA", new CountryCurrency { Code = "QAR", Symbol = "﷼" }},
            {"RE", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"RO", new CountryCurrency { Code = "RON", Symbol = "lei" }},
            {"RS", new CountryCurrency { Code = "RSD", Symbol = "Дин." }},
            {"RU", new CountryCurrency { Code = "RUB", Symbol = "₽" }},
            {"RW", new CountryCurrency { Code = "RWF", Symbol = "R₣" }},
            {"SA", new CountryCurrency { Code = "SAR", Symbol = "﷼" }},
            {"SB", new CountryCurrency { Code = "SBD", Symbol = "$" }},
            {"SC", new CountryCurrency { Code = "SCR", Symbol = "₨" }},
            {"SD", new CountryCurrency { Code = "SDG", Symbol = "ج.س." }},
            {"SE", new CountryCurrency { Code = "SEK", Symbol = "kr" }},
            {"SG", new CountryCurrency { Code = "SGD", Symbol = "S$" }},
            {"SH", new CountryCurrency { Code = "SHP", Symbol = "£" }},
            {"SI", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"SJ", new CountryCurrency { Code = "NOK", Symbol = "kr" }},
            {"SK", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"SL", new CountryCurrency { Code = "SLL", Symbol = "Le" }},
            {"SM", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"SN", new CountryCurrency { Code = "XOF", Symbol = "CFA" }},
            {"SO", new CountryCurrency { Code = "SOS", Symbol = "S" }},
            {"SR", new CountryCurrency { Code = "SRD", Symbol = "$" }},
            {"SS", new CountryCurrency { Code = "SSP", Symbol = "£" }},
            {"ST", new CountryCurrency { Code = "STD", Symbol = "Db" }},
            {"SV", new CountryCurrency { Code = "USD", Symbol = "$" }},
            {"SX", new CountryCurrency { Code = "ANG", Symbol = "ƒ" }},
            {"SY", new CountryCurrency { Code = "SYP", Symbol = "£" }},
            {"SZ", new CountryCurrency { Code = "SZL", Symbol = "E" }},
            {"TC", new CountryCurrency { Code = "USD", Symbol = "$" }},
            {"TD", new CountryCurrency { Code = "XAF", Symbol = "FCFA" }},
            {"TF", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"TG", new CountryCurrency { Code = "XOF", Symbol = "CFA" }},
            {"TH", new CountryCurrency { Code = "THB", Symbol = "฿" }},
            {"TJ", new CountryCurrency { Code = "TJS", Symbol = "SM" }},
            {"TK", new CountryCurrency { Code = "NZD", Symbol = "$" }},
            {"TL", new CountryCurrency { Code = "USD", Symbol = "$" }},
            {"TM", new CountryCurrency { Code = "TMT", Symbol = "T" }},
            {"TN", new CountryCurrency { Code = "TND", Symbol = "د.ت" }},
            {"TO", new CountryCurrency { Code = "TOP", Symbol = "T$" }},
            {"TR", new CountryCurrency { Code = "TRY", Symbol = "₺" }},
            {"TT", new CountryCurrency { Code = "TTD", Symbol = "TT$" }},
            {"TV", new CountryCurrency { Code = "AUD", Symbol = "$" }},
            {"TW", new CountryCurrency { Code = "TWD", Symbol = "NT$" }},
            {"TZ", new CountryCurrency { Code = "TZS", Symbol = "TSh" }},
            {"UA", new CountryCurrency { Code = "UAH", Symbol = "₴" }},
            {"UG", new CountryCurrency { Code = "UGX", Symbol = "USh" }},
            {"UM", new CountryCurrency { Code = "USD", Symbol = "$" }},
            {"US", new CountryCurrency { Code = "USD", Symbol = "$" }},
            {"UY", new CountryCurrency { Code = "UYU", Symbol = "$U" }},
            {"UZ", new CountryCurrency { Code = "UZS", Symbol = "лв" }},
            {"VA", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"VC", new CountryCurrency { Code = "XCD", Symbol = "$" }},
            {"VE", new CountryCurrency { Code = "VEF", Symbol = "Bs" }},
            {"VG", new CountryCurrency { Code = "USD", Symbol = "$" }},
            {"VI", new CountryCurrency { Code = "USD", Symbol = "$" }},
            {"VN", new CountryCurrency { Code = "VND", Symbol = "₫" }},
            {"VU", new CountryCurrency { Code = "VUV", Symbol = "VT" }},
            {"WF", new CountryCurrency { Code = "XPF", Symbol = "₣" }},
            {"WS", new CountryCurrency { Code = "WST", Symbol = "WS$" }},
            {"XK", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"YE", new CountryCurrency { Code = "YER", Symbol = "﷼" }},
            {"YT", new CountryCurrency { Code = "EUR", Symbol = "€" }},
            {"ZA", new CountryCurrency { Code = "ZAR", Symbol = "R" }},
            {"ZM", new CountryCurrency { Code = "ZMK", Symbol = "ZK" }},
            {"ZW", new CountryCurrency { Code = "ZWL", Symbol = "$" }}
        };

        // Static dictionary for continents
        private static readonly Dictionary<string, Continent> Continents = new Dictionary<string, Continent>
        {
            {"BD", new Continent { Code = "AS", Name = "Asia" }},
            {"BE", new Continent { Code = "EU", Name = "Europe" }},
            {"BF", new Continent { Code = "AF", Name = "Africa" }},
            {"BG", new Continent { Code = "EU", Name = "Europe" }},
            {"BA", new Continent { Code = "EU", Name = "Europe" }},
            {"BB", new Continent { Code = "NA", Name = "North America" }},
            {"WF", new Continent { Code = "OC", Name = "Oceania" }},
            {"BL", new Continent { Code = "NA", Name = "North America" }},
            {"BM", new Continent { Code = "NA", Name = "North America" }},
            {"BN", new Continent { Code = "AS", Name = "Asia" }},
            {"BO", new Continent { Code = "SA", Name = "South America" }},
            {"BH", new Continent { Code = "AS", Name = "Asia" }},
            {"BI", new Continent { Code = "AF", Name = "Africa" }},
            {"BJ", new Continent { Code = "AF", Name = "Africa" }},
            {"BT", new Continent { Code = "AS", Name = "Asia" }},
            {"JM", new Continent { Code = "NA", Name = "North America" }},
            {"BV", new Continent { Code = "AN", Name = "Antarctica" }},
            {"BW", new Continent { Code = "AF", Name = "Africa" }},
            {"WS", new Continent { Code = "OC", Name = "Oceania" }},
            {"BQ", new Continent { Code = "NA", Name = "North America" }},
            {"BR", new Continent { Code = "SA", Name = "South America" }},
            {"BS", new Continent { Code = "NA", Name = "North America" }},
            {"JE", new Continent { Code = "EU", Name = "Europe" }},
            {"BY", new Continent { Code = "EU", Name = "Europe" }},
            {"BZ", new Continent { Code = "NA", Name = "North America" }},
            {"RU", new Continent { Code = "EU", Name = "Europe" }},
            {"RW", new Continent { Code = "AF", Name = "Africa" }},
            {"RS", new Continent { Code = "EU", Name = "Europe" }},
            {"TL", new Continent { Code = "OC", Name = "Oceania" }},
            {"RE", new Continent { Code = "AF", Name = "Africa" }},
            {"TM", new Continent { Code = "AS", Name = "Asia" }},
            {"TJ", new Continent { Code = "AS", Name = "Asia" }},
            {"RO", new Continent { Code = "EU", Name = "Europe" }},
            {"TK", new Continent { Code = "OC", Name = "Oceania" }},
            {"GW", new Continent { Code = "AF", Name = "Africa" }},
            {"GU", new Continent { Code = "OC", Name = "Oceania" }},
            {"GT", new Continent { Code = "NA", Name = "North America" }},
            {"GS", new Continent { Code = "AN", Name = "Antarctica" }},
            {"GR", new Continent { Code = "EU", Name = "Europe" }},
            {"GQ", new Continent { Code = "AF", Name = "Africa" }},
            {"GP", new Continent { Code = "NA", Name = "North America" }},
            {"JP", new Continent { Code = "AS", Name = "Asia" }},
            {"GY", new Continent { Code = "SA", Name = "South America" }},
            {"GG", new Continent { Code = "EU", Name = "Europe" }},
            {"GF", new Continent { Code = "SA", Name = "South America" }},
            {"GE", new Continent { Code = "AS", Name = "Asia" }},
            {"GD", new Continent { Code = "NA", Name = "North America" }},
            {"GB", new Continent { Code = "EU", Name = "Europe" }},
            {"GA", new Continent { Code = "AF", Name = "Africa" }},
            {"SV", new Continent { Code = "NA", Name = "North America" }},
            {"GN", new Continent { Code = "AF", Name = "Africa" }},
            {"GM", new Continent { Code = "AF", Name = "Africa" }},
            {"GL", new Continent { Code = "NA", Name = "North America" }},
            {"GI", new Continent { Code = "EU", Name = "Europe" }},
            {"GH", new Continent { Code = "AF", Name = "Africa" }},
            {"OM", new Continent { Code = "AS", Name = "Asia" }},
            {"TN", new Continent { Code = "AF", Name = "Africa" }},
            {"JO", new Continent { Code = "AS", Name = "Asia" }},
            {"HR", new Continent { Code = "EU", Name = "Europe" }},
            {"HT", new Continent { Code = "NA", Name = "North America" }},
            {"HU", new Continent { Code = "EU", Name = "Europe" }},
            {"HK", new Continent { Code = "AS", Name = "Asia" }},
            {"HN", new Continent { Code = "NA", Name = "North America" }},
            {"HM", new Continent { Code = "AN", Name = "Antarctica" }},
            {"VE", new Continent { Code = "SA", Name = "South America" }},
            {"PR", new Continent { Code = "NA", Name = "North America" }},
            {"PS", new Continent { Code = "AS", Name = "Asia" }},
            {"PW", new Continent { Code = "OC", Name = "Oceania" }},
            {"PT", new Continent { Code = "EU", Name = "Europe" }},
            {"SJ", new Continent { Code = "EU", Name = "Europe" }},
            {"PY", new Continent { Code = "SA", Name = "South America" }},
            {"IQ", new Continent { Code = "AS", Name = "Asia" }},
            {"PA", new Continent { Code = "NA", Name = "North America" }},
            {"PF", new Continent { Code = "OC", Name = "Oceania" }},
            {"PG", new Continent { Code = "OC", Name = "Oceania" }},
            {"PE", new Continent { Code = "SA", Name = "South America" }},
            {"PK", new Continent { Code = "AS", Name = "Asia" }},
            {"PH", new Continent { Code = "AS", Name = "Asia" }},
            {"PN", new Continent { Code = "OC", Name = "Oceania" }},
            {"PL", new Continent { Code = "EU", Name = "Europe" }},
            {"PM", new Continent { Code = "NA", Name = "North America" }},
            {"ZM", new Continent { Code = "AF", Name = "Africa" }},
            {"EH", new Continent { Code = "AF", Name = "Africa" }},
            {"EE", new Continent { Code = "EU", Name = "Europe" }},
            {"EG", new Continent { Code = "AF", Name = "Africa" }},
            {"ZA", new Continent { Code = "AF", Name = "Africa" }},
            {"EC", new Continent { Code = "SA", Name = "South America" }},
            {"IT", new Continent { Code = "EU", Name = "Europe" }},
            {"VN", new Continent { Code = "AS", Name = "Asia" }},
            {"SB", new Continent { Code = "OC", Name = "Oceania" }},
            {"ET", new Continent { Code = "AF", Name = "Africa" }},
            {"SO", new Continent { Code = "AF", Name = "Africa" }},
            {"ZW", new Continent { Code = "AF", Name = "Africa" }},
            {"SA", new Continent { Code = "AS", Name = "Asia" }},
            {"ES", new Continent { Code = "EU", Name = "Europe" }},
            {"ER", new Continent { Code = "AF", Name = "Africa" }},
            {"ME", new Continent { Code = "EU", Name = "Europe" }},
            {"MD", new Continent { Code = "EU", Name = "Europe" }},
            {"MG", new Continent { Code = "AF", Name = "Africa" }},
            {"MF", new Continent { Code = "NA", Name = "North America" }},
            {"MA", new Continent { Code = "AF", Name = "Africa" }},
            {"MC", new Continent { Code = "EU", Name = "Europe" }},
            {"UZ", new Continent { Code = "AS", Name = "Asia" }},
            {"MM", new Continent { Code = "AS", Name = "Asia" }},
            {"ML", new Continent { Code = "AF", Name = "Africa" }},
            {"MO", new Continent { Code = "AS", Name = "Asia" }},
            {"MN", new Continent { Code = "AS", Name = "Asia" }},
            {"MH", new Continent { Code = "OC", Name = "Oceania" }},
            {"MK", new Continent { Code = "EU", Name = "Europe" }},
            {"MU", new Continent { Code = "AF", Name = "Africa" }},
            {"MT", new Continent { Code = "EU", Name = "Europe" }},
            {"MW", new Continent { Code = "AF", Name = "Africa" }},
            {"MV", new Continent { Code = "AS", Name = "Asia" }},
            {"MQ", new Continent { Code = "NA", Name = "North America" }},
            {"MP", new Continent { Code = "OC", Name = "Oceania" }},
            {"MS", new Continent { Code = "NA", Name = "North America" }},
            {"MR", new Continent { Code = "AF", Name = "Africa" }},
            {"IM", new Continent { Code = "EU", Name = "Europe" }},
            {"UG", new Continent { Code = "AF", Name = "Africa" }},
            {"TZ", new Continent { Code = "AF", Name = "Africa" }},
            {"MY", new Continent { Code = "AS", Name = "Asia" }},
            {"MX", new Continent { Code = "NA", Name = "North America" }},
            {"IL", new Continent { Code = "AS", Name = "Asia" }},
            {"FR", new Continent { Code = "EU", Name = "Europe" }},
            {"IO", new Continent { Code = "AS", Name = "Asia" }},
            {"SH", new Continent { Code = "AF", Name = "Africa" }},
            {"FI", new Continent { Code = "EU", Name = "Europe" }},
            {"FJ", new Continent { Code = "OC", Name = "Oceania" }},
            {"FK", new Continent { Code = "SA", Name = "South America" }},
            {"FM", new Continent { Code = "OC", Name = "Oceania" }},
            {"FO", new Continent { Code = "EU", Name = "Europe" }},
            {"NI", new Continent { Code = "NA", Name = "North America" }},
            {"NL", new Continent { Code = "EU", Name = "Europe" }},
            {"NO", new Continent { Code = "EU", Name = "Europe" }},
            {"NA", new Continent { Code = "AF", Name = "Africa" }},
            {"VU", new Continent { Code = "OC", Name = "Oceania" }},
            {"NC", new Continent { Code = "OC", Name = "Oceania" }},
            {"NE", new Continent { Code = "AF", Name = "Africa" }},
            {"NF", new Continent { Code = "OC", Name = "Oceania" }},
            {"NG", new Continent { Code = "AF", Name = "Africa" }},
            {"NZ", new Continent { Code = "OC", Name = "Oceania" }},
            {"NP", new Continent { Code = "AS", Name = "Asia" }},
            {"NR", new Continent { Code = "OC", Name = "Oceania" }},
            {"NU", new Continent { Code = "OC", Name = "Oceania" }},
            {"CK", new Continent { Code = "OC", Name = "Oceania" }},
            {"XK", new Continent { Code = "EU", Name = "Europe" }},
            {"CI", new Continent { Code = "AF", Name = "Africa" }},
            {"CH", new Continent { Code = "EU", Name = "Europe" }},
            {"CO", new Continent { Code = "SA", Name = "South America" }},
            {"CN", new Continent { Code = "AS", Name = "Asia" }},
            {"CM", new Continent { Code = "AF", Name = "Africa" }},
            {"CL", new Continent { Code = "SA", Name = "South America" }},
            {"CC", new Continent { Code = "AS", Name = "Asia" }},
            {"CA", new Continent { Code = "NA", Name = "North America" }},
            {"CG", new Continent { Code = "AF", Name = "Africa" }},
            {"CF", new Continent { Code = "AF", Name = "Africa" }},
            {"CD", new Continent { Code = "AF", Name = "Africa" }},
            {"CZ", new Continent { Code = "EU", Name = "Europe" }},
            {"CY", new Continent { Code = "EU", Name = "Europe" }},
            {"CX", new Continent { Code = "AS", Name = "Asia" }},
            {"CR", new Continent { Code = "NA", Name = "North America" }},
            {"CW", new Continent { Code = "NA", Name = "North America" }},
            {"CV", new Continent { Code = "AF", Name = "Africa" }},
            {"CU", new Continent { Code = "NA", Name = "North America" }},
            {"SZ", new Continent { Code = "AF", Name = "Africa" }},
            {"SY", new Continent { Code = "AS", Name = "Asia" }},
            {"SX", new Continent { Code = "NA", Name = "North America" }},
            {"KG", new Continent { Code = "AS", Name = "Asia" }},
            {"KE", new Continent { Code = "AF", Name = "Africa" }},
            {"SS", new Continent { Code = "AF", Name = "Africa" }},
            {"SR", new Continent { Code = "SA", Name = "South America" }},
            {"KI", new Continent { Code = "OC", Name = "Oceania" }},
            {"KH", new Continent { Code = "AS", Name = "Asia" }},
            {"KN", new Continent { Code = "NA", Name = "North America" }},
            {"KM", new Continent { Code = "AF", Name = "Africa" }},
            {"ST", new Continent { Code = "AF", Name = "Africa" }},
            {"SK", new Continent { Code = "EU", Name = "Europe" }},
            {"KR", new Continent { Code = "AS", Name = "Asia" }},
            {"SI", new Continent { Code = "EU", Name = "Europe" }},
            {"KP", new Continent { Code = "AS", Name = "Asia" }},
            {"KW", new Continent { Code = "AS", Name = "Asia" }},
            {"SN", new Continent { Code = "AF", Name = "Africa" }},
            {"SM", new Continent { Code = "EU", Name = "Europe" }},
            {"SL", new Continent { Code = "AF", Name = "Africa" }},
            {"SC", new Continent { Code = "AF", Name = "Africa" }},
            {"KZ", new Continent { Code = "AS", Name = "Asia" }},
            {"KY", new Continent { Code = "NA", Name = "North America" }},
            {"SG", new Continent { Code = "AS", Name = "Asia" }},
            {"SE", new Continent { Code = "EU", Name = "Europe" }},
            {"SD", new Continent { Code = "AF", Name = "Africa" }},
            {"DO", new Continent { Code = "NA", Name = "North America" }},
            {"DM", new Continent { Code = "NA", Name = "North America" }},
            {"DJ", new Continent { Code = "AF", Name = "Africa" }},
            {"DK", new Continent { Code = "EU", Name = "Europe" }},
            {"VG", new Continent { Code = "NA", Name = "North America" }},
            {"DE", new Continent { Code = "EU", Name = "Europe" }},
            {"YE", new Continent { Code = "AS", Name = "Asia" }},
            {"DZ", new Continent { Code = "AF", Name = "Africa" }},
            {"US", new Continent { Code = "NA", Name = "North America" }},
            {"UY", new Continent { Code = "SA", Name = "South America" }},
            {"YT", new Continent { Code = "AF", Name = "Africa" }},
            {"UM", new Continent { Code = "OC", Name = "Oceania" }},
            {"LB", new Continent { Code = "AS", Name = "Asia" }},
            {"LC", new Continent { Code = "NA", Name = "North America" }},
            {"LA", new Continent { Code = "AS", Name = "Asia" }},
            {"TV", new Continent { Code = "OC", Name = "Oceania" }},
            {"TW", new Continent { Code = "AS", Name = "Asia" }},
            {"TT", new Continent { Code = "NA", Name = "North America" }},
            {"TR", new Continent { Code = "AS", Name = "Asia" }},
            {"LK", new Continent { Code = "AS", Name = "Asia" }},
            {"LI", new Continent { Code = "EU", Name = "Europe" }},
            {"LV", new Continent { Code = "EU", Name = "Europe" }},
            {"TO", new Continent { Code = "OC", Name = "Oceania" }},
            {"LT", new Continent { Code = "EU", Name = "Europe" }},
            {"LU", new Continent { Code = "EU", Name = "Europe" }},
            {"LR", new Continent { Code = "AF", Name = "Africa" }},
            {"LS", new Continent { Code = "AF", Name = "Africa" }},
            {"TH", new Continent { Code = "AS", Name = "Asia" }},
            {"TF", new Continent { Code = "AN", Name = "Antarctica" }},
            {"TG", new Continent { Code = "AF", Name = "Africa" }},
            {"TD", new Continent { Code = "AF", Name = "Africa" }},
            {"TC", new Continent { Code = "NA", Name = "North America" }},
            {"LY", new Continent { Code = "AF", Name = "Africa" }},
            {"VA", new Continent { Code = "EU", Name = "Europe" }},
            {"VC", new Continent { Code = "NA", Name = "North America" }},
            {"AE", new Continent { Code = "AS", Name = "Asia" }},
            {"AD", new Continent { Code = "EU", Name = "Europe" }},
            {"AG", new Continent { Code = "NA", Name = "North America" }},
            {"AF", new Continent { Code = "AS", Name = "Asia" }},
            {"AI", new Continent { Code = "NA", Name = "North America" }},
            {"VI", new Continent { Code = "NA", Name = "North America" }},
            {"IS", new Continent { Code = "EU", Name = "Europe" }},
            {"IR", new Continent { Code = "AS", Name = "Asia" }},
            {"AM", new Continent { Code = "AS", Name = "Asia" }},
            {"AL", new Continent { Code = "EU", Name = "Europe" }},
            {"AO", new Continent { Code = "AF", Name = "Africa" }},
            {"AQ", new Continent { Code = "AN", Name = "Antarctica" }},
            {"AS", new Continent { Code = "OC", Name = "Oceania" }},
            {"AR", new Continent { Code = "SA", Name = "South America" }},
            {"AU", new Continent { Code = "OC", Name = "Oceania" }},
            {"AT", new Continent { Code = "EU", Name = "Europe" }},
            {"AW", new Continent { Code = "NA", Name = "North America" }},
            {"IN", new Continent { Code = "AS", Name = "Asia" }},
            {"AX", new Continent { Code = "EU", Name = "Europe" }},
            {"AZ", new Continent { Code = "AS", Name = "Asia" }},
            {"IE", new Continent { Code = "EU", Name = "Europe" }},
            {"ID", new Continent { Code = "AS", Name = "Asia" }},
            {"UA", new Continent { Code = "EU", Name = "Europe" }},
            {"QA", new Continent { Code = "AS", Name = "Asia" }},
            {"MZ", new Continent { Code = "AF", Name = "Africa" }}
        };

        // Static list for EU countries
        private static readonly List<string> EUCountries = new List<string>
        {
            "IE",
            "AT",
            "LT",
            "LU",
            "LV",
            "DE",
            "DK",
            "SE",
            "SI",
            "SK",
            "CZ",
            "CY",
            "NL",
            "FI",
            "FR",
            "MT",
            "ES",
            "IT",
            "EE",
            "PL",
            "PT",
            "HU",
            "HR",
            "GR",
            "RO",
            "BG",
            "BE"
        };

        /// <summary>
        /// Gets full country name against country code.
        /// </summary>
        /// <param name="countryCode">Country code consisting of two characters.</param>
        /// <returns>The full country name. If country code is not found in the dictionary, then same country code is returned.</returns>
        internal static string GetCountry(string countryCode)
        {
            if (countryCode == null)
            {
                return null;
            }

            if (Countries.ContainsKey(countryCode))
            {
                return Countries[countryCode];
            }
            else
            {
                return countryCode;
            }
        }

        /// <summary>
        /// whether a country is a member of the EU or not.
        /// </summary>
        /// <param name="countryCode">Country code consisting of two characters.</param>
        /// <returns>True if the country is a member of the European Union (EU) else false.</returns>
        internal static bool IsEU(string countryCode)
        {
            if (countryCode == null)
            {
                return false;
            }
            return EUCountries.Contains(countryCode);
        }

        /// <summary>
        /// Gets country flag against country code.
        /// "PK" -> CountryFlag:{Emoji:"🇵🇰", Unicode:"U+1F1F5 U+1F1F0"}
        /// </summary>
        /// <param name="countryCode">Country code consisting of two characters.</param>
        /// <returns>CountryFlag of the country.</returns>
        internal static CountryFlag GetCountryFlag(string countryCode)
        {
            if (countryCode == null)
            {
                return null;
            }

            if (CountriesFlags.ContainsKey(countryCode))
            {
                return CountriesFlags[countryCode];
            }
            else
            {
                return null;
            }
        }

        /// <summary>
        /// Gets country currency against country code.
        /// {"PK" -> CountryCurrency:{ "code", "PKR"} ,{"symbol", "₨"}}
        /// </summary>
        /// <param name="countryCode">Country code consisting of two characters.</param>
        /// <returns>CountryCurrency of the country.</returns>
        internal static CountryCurrency GetCountryCurrency(string countryCode)
        {
            if (countryCode == null)
            {
                return null;
            }

            if (CountriesCurrencies.ContainsKey(countryCode))
            {
                return CountriesCurrencies[countryCode];
            }
            else
            {
                return null;
            }
        }

        /// <summary>
        /// Gets continent against country code.
        /// {"PK" -> Continent:{ "code", "AS"} ,{"name", "Asia"}}
        /// </summary>
        /// <param name="countryCode">Country code consisting of two characters.</param>
        /// <returns>Continent.</returns>
        internal static Continent GetContinent(string countryCode)
        {
            if (countryCode == null)
            {
                return null;
            }

            if (Continents.ContainsKey(countryCode))
            {
                return Continents[countryCode];
            }
            else
            {
                return null;
            }
        }
    }
}
